#db
spring:
  datasource:
    url: jdbc:mysql://192.168.1.144:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 21316002
  redis:
    host: 192.168.1.144
    port: 6379
